### ISSUE TITLE
Test across all the App

### ISSUE THREAD

**Issue by MichaelLucca** [jod-li/flutster#4]
Hello!😁
I have. a question: Is it possible to use Flutster across all the app and not only limited to the single Scaffold/Widget?

**Comment by lcuis** [comment]
Hi @MichaelLucca , sorry for the late reply.

Theoretically, it should be possible to test across different Flutster scaffolds.

**Comment by lcuis** [comment]
In fact, I have a doubt but I'm having network issues preventing compilation for me to test.

**Comment by lcuis** [comment]
I am now able to compile with version 1.1.1 but the KeyboardListener now doesn't report events when focused on a text field. I am trying to find a solution.

**Comment by lcuis** [comment]
I tried many options to solve this keyboard listening problem.
I am left with the following possibilities for now. None of which are great:
1. Customize Flutter SDK to make it possible to listen to keyboard outside EditableText widgets. This involves a lot of potential issues each time there is an update of the framework.
2. Find a way to customize the onscreen keyboard and listen to keys from there.
3. Let the user reenter the text manually when editing the test.

**Comment by MichaelLucca** [comment]
Hi @lcuis 😁
First of all, thank you for your support! I tried again, and I can confirm that the test works across multiple FlutsterScaffold.

I didn’t fully understand what issues there might be with the keyboard.
Additionally, I’m trying to run a test fetched from the API, but I keep encountering the same error:

`Warning: failed to get the state: Bad state: No element  
#0      Iterable.firstWhere (dart:core/iterable.dart:702:5)  
#1      FlutsterTestEvent.recorderState (package:flutster/flutster.dart:1059:39)  
#2      FlutsterTestEvent.play (package:flutster/flutster.dart:1701:31)  
#3      FlutsterTestRecord.play (package:flutster/flutster.dart:705:33)  
#4      FlutsterTestRecord.playToApi (package:flutster/flutster.dart:690:22)  
#5      main.<anonymous closure> (ntegration_test/flutster/flutster_test.dart:29:33)  
<asynchronous suspension>  
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)  
<asynchronous suspension>`

**Comment by lcuis** [comment]
Hello @MichaelLucca ,

Thanks for letting me know. I will look into this as soon as I can.

**Comment by lcuis** [comment]
@MichaelLucca ,

Theorectically, this is just a warning that could happen at the beginning of the test run.
However, you should have more chances to see this warning disappear with the more retries are being executed since the tester is being pumped at each retry.
The maximum number of retries is set to 10. I hope the number of retries is not exhausted in your case?
This would be visible with this message: "Warning: exhausted retries trying to get the new state".

**Comment by MichaelLucca** [comment]
@lcuis,
I think the problem might be related to some ProgressIndicators that are appearing on screen?

Regarding the keyboard listening issue, if I understand correctly, are you saying that it’s currently not possible to fill any of the TextFields with the value recorded during the test?

**Comment by lcuis** [comment]
Oh, ok, I will look into this progress issue. Is this blocking the run execution?

Yes, the latest Flutter release has rendered obsolete the means Flutster had to record the keyboard interaction details when the focus is on TextEdit widgets such as form fields. This makes Flutster much less usable. I still did not find any satisfactory workaround/solution. The only possibility for now seems to be the recognition that such an event occurred and the user will have to fill the text manually. That was not the purpose of Flutster which was meant to be a convenient test recording tool.

**Comment by MichaelLucca** [comment]
Yes, this is indeed blocking the execution. I’ve tried hiding the ProgressIndicators, and the test proceeds correctly after that.

For now, I’ll try to work around the TextFields issue.

I’m looking forward to using Flutster at its full potential again!
